spring.application.name=Azizul

# MongoDB Atlas
spring.mongodb.uri=mongodb+srv://azizul:MLwqPZwcU7WqNUbL@ase-naki-mongo.vcdwgus.mongodb.net/mission_db?appName=Ase-Naki-Mongo
spring.mongodb.database=mission_db
spring.data.mongodb.auto-index-creation=true

# Server
server.port=${PORT:8080}
server.address=0.0.0.0

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always