spring.application.name=Azizul

# MongoDB
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE:mission_db}
spring.data.mongodb.auto-index-creation=true

# Server
server.port=${PORT:8080}
server.address=0.0.0.0
server.forward-headers-strategy=framework

# Thymeleaf
spring.thymeleaf.cache=${THYMELEAF_CACHE:false}
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Error handling
server.error.include-message=never

# Session Security
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax